name: Publish Package
on:
  release:
    types: created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: mindstorm/setup-emsdk@v11
      
      - run: emcc -v
    
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'

      - run: yarn
      
      - run: ./build.sh package

      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
